version: '2.1'

services:
  mongo:
    image: mongo:3.4.15
    restart: always
    expose:
      - "27017"
    volumes:
      - 'mongodb:/var/lib/mongodb/data'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    expose:
      - '6379'
    volumes:
      - 'redis:/var/lib/redis/data'
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    image: crypto_news
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - redis
    env_file:
      - '.env'

volumes:
  redis:
  mongodb:
